name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: 'latest'
        cabal-version: 'latest'
    - name: Cache cabal
      id: cache-cabal
      uses: actions/cache@v1
      with:
        path: /home/runner/.cabal
        key: ${{ runner.os }}-cabal
    - name: Install dependencies
      run: |
        cabal update
        cabal install --only-dependencies --overwrite-policy=always
    - name: Install boost
      run: |
        git clone https://github.com/boostorg/build.git
        cd build
        ./bootstrap.sh
        sudo ./b2 install --prefix=/usr/local
    - name: Build
      run: |
        cabal configure
        cabal build
    - name: ctest
      run: |
        /usr/local/bin/b2 ctest
