name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
    - name: Install dependencies
      run: |
        cabal update
        cabal install --only-dependencies
    - name: Install boost
      run: |
        git clone https://github.com/boostorg/build.git
        cd build
        ./bootstrap.sh
        ./b2 install --prefix=/usr/local
    - name: Build
      run: |
        cabal configure
        cabal build
    - name: ctest
      run: |
        bjam ctest
